### PR TITLE
feat: Fixes: #6 Added decorators in all routes

### LINKED ISSUE #6: Add @token_required decorator to all the routes
Just need to add @token_required decorator to all the available routes in app.py

### PR DESCRIPTION
**Pull request by Preet-taparia**
feat: Fixes: #6 Added decorators in all routes

### CODE REVIEW

**Comment by Preet-taparia** [comment]
Hey @bbhupen , can you please put the label of hacktoberfest-accepted on it. and add label of hacktoberfest on the repo also add a contributing.md file (follow this link: https://hacktoberfest.com/participation/#maintainers )

**Comment by bbhupen** [comment]
@Preet-taparia 
Sure I forgot about that, will do it now

**Comment by Preet-taparia** [comment]
@bbhupen thanks for adding label just one last sthing add a contributing.md file

**Comment by bbhupen** [comment]
@Preet-taparia yeah I was looking on that, I was just caught up with some work. Would you mind taking up this issue and raise a PR? I'll merge it

**Comment by Preet-taparia** [comment]
Okay, i will try

**Pull request merged**
